//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobTitleBean", Namespace="http://webservice.hrm.weaver")]
    public partial class JobTitleBean : object
    {
        
        private string _codeField;
        
        private string _departmentidField;
        
        private string _fullnameField;
        
        private string _jobcompetencyField;
        
        private string _jobdocField;
        
        private string _jobresponsibilityField;
        
        private string _jobtitleidField;
        
        private string _jobtitleremarkField;
        
        private string _lastChangdateField;
        
        private string _shortnameField;
        
        private string actionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _code
        {
            get
            {
                return this._codeField;
            }
            set
            {
                this._codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _departmentid
        {
            get
            {
                return this._departmentidField;
            }
            set
            {
                this._departmentidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _fullname
        {
            get
            {
                return this._fullnameField;
            }
            set
            {
                this._fullnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _jobcompetency
        {
            get
            {
                return this._jobcompetencyField;
            }
            set
            {
                this._jobcompetencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _jobdoc
        {
            get
            {
                return this._jobdocField;
            }
            set
            {
                this._jobdocField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _jobresponsibility
        {
            get
            {
                return this._jobresponsibilityField;
            }
            set
            {
                this._jobresponsibilityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _jobtitleid
        {
            get
            {
                return this._jobtitleidField;
            }
            set
            {
                this._jobtitleidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _jobtitleremark
        {
            get
            {
                return this._jobtitleremarkField;
            }
            set
            {
                this._jobtitleremarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _lastChangdate
        {
            get
            {
                return this._lastChangdateField;
            }
            set
            {
                this._lastChangdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _shortname
        {
            get
            {
                return this._shortnameField;
            }
            set
            {
                this._shortnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubCompanyBean", Namespace="http://webservice.hrm.weaver")]
    public partial class SubCompanyBean : object
    {
        
        private string _canceledField;
        
        private string _codeField;
        
        private string _fullnameField;
        
        private string _shortnameField;
        
        private string _showorderField;
        
        private string _subcompanyidField;
        
        private string _supsubcompanyidField;
        
        private string _websiteField;
        
        private string actionField;
        
        private string lastChangdateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _canceled
        {
            get
            {
                return this._canceledField;
            }
            set
            {
                this._canceledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _code
        {
            get
            {
                return this._codeField;
            }
            set
            {
                this._codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _fullname
        {
            get
            {
                return this._fullnameField;
            }
            set
            {
                this._fullnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _shortname
        {
            get
            {
                return this._shortnameField;
            }
            set
            {
                this._shortnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _showorder
        {
            get
            {
                return this._showorderField;
            }
            set
            {
                this._showorderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _subcompanyid
        {
            get
            {
                return this._subcompanyidField;
            }
            set
            {
                this._subcompanyidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _supsubcompanyid
        {
            get
            {
                return this._supsubcompanyidField;
            }
            set
            {
                this._supsubcompanyidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _website
        {
            get
            {
                return this._websiteField;
            }
            set
            {
                this._websiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastChangdate
        {
            get
            {
                return this.lastChangdateField;
            }
            set
            {
                this.lastChangdateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserBean", Namespace="http://webservice.hrm.weaver")]
    public partial class UserBean : object
    {
        
        private int accounttypeField;
        
        private string assistantidField;
        
        private string bememberdateField;
        
        private string bepartydateField;
        
        private string birthdayField;
        
        private string certificatenumField;
        
        private string createdateField;
        
        private string degreeField;
        
        private string departmentcodeField;
        
        private string departmentidField;
        
        private string departmentnameField;
        
        private float dsporderField;
        
        private string educationlevelField;
        
        private string emailField;
        
        private string enddateField;
        
        private string faxField;
        
        private string folkField;
        
        private string healthinfoField;
        
        private string heightField;
        
        private string homeaddressField;
        
        private string islabouunionField;
        
        private string jobactivitydescField;
        
        private string jobactivityidField;
        
        private string jobcallField;
        
        private string jobgroupidField;
        
        private string joblevelField;
        
        private string jobtitleField;
        
        private string lastChangdateField;
        
        private string lastnameField;
        
        private string locationidField;
        
        private string loginidField;
        
        private string manageridField;
        
        private string maritalstatusField;
        
        private string mobileField;
        
        private string mobilecallField;
        
        private string nativeplaceField;
        
        private string passwordField;
        
        private string policyField;
        
        private string regresidentplaceField;
        
        private string residentplaceField;
        
        private string seclevelField;
        
        private string sexField;
        
        private string startdateField;
        
        private string statusField;
        
        private string subcompanycodeField;
        
        private string subcompanyid1Field;
        
        private string subcompanynameField;
        
        private string systemlanguageField;
        
        private string telephoneField;
        
        private string tempresidentnumberField;
        
        private int useridField;
        
        private string weightField;
        
        private string workcodeField;
        
        private string workroomField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int accounttype
        {
            get
            {
                return this.accounttypeField;
            }
            set
            {
                this.accounttypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string assistantid
        {
            get
            {
                return this.assistantidField;
            }
            set
            {
                this.assistantidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bememberdate
        {
            get
            {
                return this.bememberdateField;
            }
            set
            {
                this.bememberdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bepartydate
        {
            get
            {
                return this.bepartydateField;
            }
            set
            {
                this.bepartydateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string birthday
        {
            get
            {
                return this.birthdayField;
            }
            set
            {
                this.birthdayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string certificatenum
        {
            get
            {
                return this.certificatenumField;
            }
            set
            {
                this.certificatenumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string createdate
        {
            get
            {
                return this.createdateField;
            }
            set
            {
                this.createdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string degree
        {
            get
            {
                return this.degreeField;
            }
            set
            {
                this.degreeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departmentcode
        {
            get
            {
                return this.departmentcodeField;
            }
            set
            {
                this.departmentcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departmentid
        {
            get
            {
                return this.departmentidField;
            }
            set
            {
                this.departmentidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departmentname
        {
            get
            {
                return this.departmentnameField;
            }
            set
            {
                this.departmentnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float dsporder
        {
            get
            {
                return this.dsporderField;
            }
            set
            {
                this.dsporderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string educationlevel
        {
            get
            {
                return this.educationlevelField;
            }
            set
            {
                this.educationlevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string enddate
        {
            get
            {
                return this.enddateField;
            }
            set
            {
                this.enddateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fax
        {
            get
            {
                return this.faxField;
            }
            set
            {
                this.faxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string folk
        {
            get
            {
                return this.folkField;
            }
            set
            {
                this.folkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string healthinfo
        {
            get
            {
                return this.healthinfoField;
            }
            set
            {
                this.healthinfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string homeaddress
        {
            get
            {
                return this.homeaddressField;
            }
            set
            {
                this.homeaddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string islabouunion
        {
            get
            {
                return this.islabouunionField;
            }
            set
            {
                this.islabouunionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobactivitydesc
        {
            get
            {
                return this.jobactivitydescField;
            }
            set
            {
                this.jobactivitydescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobactivityid
        {
            get
            {
                return this.jobactivityidField;
            }
            set
            {
                this.jobactivityidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobcall
        {
            get
            {
                return this.jobcallField;
            }
            set
            {
                this.jobcallField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobgroupid
        {
            get
            {
                return this.jobgroupidField;
            }
            set
            {
                this.jobgroupidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string joblevel
        {
            get
            {
                return this.joblevelField;
            }
            set
            {
                this.joblevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobtitle
        {
            get
            {
                return this.jobtitleField;
            }
            set
            {
                this.jobtitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastChangdate
        {
            get
            {
                return this.lastChangdateField;
            }
            set
            {
                this.lastChangdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname
        {
            get
            {
                return this.lastnameField;
            }
            set
            {
                this.lastnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string locationid
        {
            get
            {
                return this.locationidField;
            }
            set
            {
                this.locationidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginid
        {
            get
            {
                return this.loginidField;
            }
            set
            {
                this.loginidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string managerid
        {
            get
            {
                return this.manageridField;
            }
            set
            {
                this.manageridField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maritalstatus
        {
            get
            {
                return this.maritalstatusField;
            }
            set
            {
                this.maritalstatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mobilecall
        {
            get
            {
                return this.mobilecallField;
            }
            set
            {
                this.mobilecallField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nativeplace
        {
            get
            {
                return this.nativeplaceField;
            }
            set
            {
                this.nativeplaceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string policy
        {
            get
            {
                return this.policyField;
            }
            set
            {
                this.policyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string regresidentplace
        {
            get
            {
                return this.regresidentplaceField;
            }
            set
            {
                this.regresidentplaceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string residentplace
        {
            get
            {
                return this.residentplaceField;
            }
            set
            {
                this.residentplaceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string seclevel
        {
            get
            {
                return this.seclevelField;
            }
            set
            {
                this.seclevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sex
        {
            get
            {
                return this.sexField;
            }
            set
            {
                this.sexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string startdate
        {
            get
            {
                return this.startdateField;
            }
            set
            {
                this.startdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subcompanycode
        {
            get
            {
                return this.subcompanycodeField;
            }
            set
            {
                this.subcompanycodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subcompanyid1
        {
            get
            {
                return this.subcompanyid1Field;
            }
            set
            {
                this.subcompanyid1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subcompanyname
        {
            get
            {
                return this.subcompanynameField;
            }
            set
            {
                this.subcompanynameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string systemlanguage
        {
            get
            {
                return this.systemlanguageField;
            }
            set
            {
                this.systemlanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telephone
        {
            get
            {
                return this.telephoneField;
            }
            set
            {
                this.telephoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tempresidentnumber
        {
            get
            {
                return this.tempresidentnumberField;
            }
            set
            {
                this.tempresidentnumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userid
        {
            get
            {
                return this.useridField;
            }
            set
            {
                this.useridField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string workcode
        {
            get
            {
                return this.workcodeField;
            }
            set
            {
                this.workcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string workroom
        {
            get
            {
                return this.workroomField;
            }
            set
            {
                this.workroomField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentBean", Namespace="http://webservice.hrm.weaver")]
    public partial class DepartmentBean : object
    {
        
        private string _canceledField;
        
        private string _codeField;
        
        private string _departmentidField;
        
        private string _fullnameField;
        
        private string _shortnameField;
        
        private string _showorderField;
        
        private string _subcompanyidField;
        
        private string _supdepartmentidField;
        
        private string actionField;
        
        private string lastChangdateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _canceled
        {
            get
            {
                return this._canceledField;
            }
            set
            {
                this._canceledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _code
        {
            get
            {
                return this._codeField;
            }
            set
            {
                this._codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _departmentid
        {
            get
            {
                return this._departmentidField;
            }
            set
            {
                this._departmentidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _fullname
        {
            get
            {
                return this._fullnameField;
            }
            set
            {
                this._fullnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _shortname
        {
            get
            {
                return this._shortnameField;
            }
            set
            {
                this._shortnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _showorder
        {
            get
            {
                return this._showorderField;
            }
            set
            {
                this._showorderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _subcompanyid
        {
            get
            {
                return this._subcompanyidField;
            }
            set
            {
                this._subcompanyidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _supdepartmentid
        {
            get
            {
                return this._supdepartmentidField;
            }
            set
            {
                this._supdepartmentidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastChangdate
        {
            get
            {
                return this.lastChangdateField;
            }
            set
            {
                this.lastChangdateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/services/HrmService", ConfigurationName="ServiceReference2.HrmServicePortType")]
    public interface HrmServicePortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.hrm.webservice.HrmService.changeUserPassword", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<bool> changeUserPasswordAsync(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.hrm.webservice.HrmService.getHrmJobTitleInfoXML", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> getHrmJobTitleInfoXMLAsync(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.hrm.webservice.HrmService.getDepartmentInfoWithPage", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> getDepartmentInfoWithPageAsync(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.hrm.webservice.HrmService.getHrmDepartmentInfoXML", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> getHrmDepartmentInfoXMLAsync(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.hrm.webservice.HrmService.SynSubCompany", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> SynSubCompanyAsync(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.hrm.webservice.HrmService.getHrmJobTitleInfo", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<ServiceReference2.JobTitleBean[]> getHrmJobTitleInfoAsync(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.hrm.webservice.HrmService.getHrmSubcompanyInfo", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<ServiceReference2.SubCompanyBean[]> getHrmSubcompanyInfoAsync(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.hrm.webservice.HrmService.getOneUserInfo", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> getOneUserInfoAsync(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.hrm.webservice.HrmService.SynDepartment", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> SynDepartmentAsync(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.hrm.webservice.HrmService.getHrmUserInfo", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<ServiceReference2.UserBean[]> getHrmUserInfoAsync(string in0, string in1, string in2, string in3, string in4, string in5);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.hrm.webservice.HrmService.checkUser", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<bool> checkUserAsync(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.hrm.webservice.HrmService.getJobtitleInfoWithPage", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> getJobtitleInfoWithPageAsync(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.hrm.webservice.HrmService.SynHrmResource", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> SynHrmResourceAsync(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.hrm.webservice.HrmService.getHrmDepartmentInfo", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<ServiceReference2.DepartmentBean[]> getHrmDepartmentInfoAsync(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.hrm.webservice.HrmService.getHrmUserInfoWithPage", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> getHrmUserInfoWithPageAsync(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.hrm.webservice.HrmService.getHrmSubcompanyInfoWithPage", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> getHrmSubcompanyInfoWithPageAsync(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.hrm.webservice.HrmService.SynJobtitle", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> SynJobtitleAsync(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.hrm.webservice.HrmService.getHrmSubcompanyInfoXML", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> getHrmSubcompanyInfoXMLAsync(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.hrm.webservice.HrmService.getHrmUserInfoXML", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> getHrmUserInfoXMLAsync(string in0, string in1, string in2, string in3, string in4, string in5);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface HrmServicePortTypeChannel : ServiceReference2.HrmServicePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class HrmServicePortTypeClient : System.ServiceModel.ClientBase<ServiceReference2.HrmServicePortType>, ServiceReference2.HrmServicePortType
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HrmServicePortTypeClient() : 
                base(HrmServicePortTypeClient.GetDefaultBinding(), HrmServicePortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.HrmServiceHttpPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HrmServicePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(HrmServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), HrmServicePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HrmServicePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HrmServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HrmServicePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HrmServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HrmServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> changeUserPasswordAsync(string in0, string in1, string in2)
        {
            return base.Channel.changeUserPasswordAsync(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<string> getHrmJobTitleInfoXMLAsync(string in0, string in1, string in2)
        {
            return base.Channel.getHrmJobTitleInfoXMLAsync(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<string> getDepartmentInfoWithPageAsync(string in0)
        {
            return base.Channel.getDepartmentInfoWithPageAsync(in0);
        }
        
        public System.Threading.Tasks.Task<string> getHrmDepartmentInfoXMLAsync(string in0, string in1)
        {
            return base.Channel.getHrmDepartmentInfoXMLAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<string> SynSubCompanyAsync(string in0, string in1)
        {
            return base.Channel.SynSubCompanyAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.JobTitleBean[]> getHrmJobTitleInfoAsync(string in0, string in1, string in2)
        {
            return base.Channel.getHrmJobTitleInfoAsync(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.SubCompanyBean[]> getHrmSubcompanyInfoAsync(string in0)
        {
            return base.Channel.getHrmSubcompanyInfoAsync(in0);
        }
        
        public System.Threading.Tasks.Task<string> getOneUserInfoAsync(string in0)
        {
            return base.Channel.getOneUserInfoAsync(in0);
        }
        
        public System.Threading.Tasks.Task<string> SynDepartmentAsync(string in0, string in1)
        {
            return base.Channel.SynDepartmentAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.UserBean[]> getHrmUserInfoAsync(string in0, string in1, string in2, string in3, string in4, string in5)
        {
            return base.Channel.getHrmUserInfoAsync(in0, in1, in2, in3, in4, in5);
        }
        
        public System.Threading.Tasks.Task<bool> checkUserAsync(string in0, string in1, string in2)
        {
            return base.Channel.checkUserAsync(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<string> getJobtitleInfoWithPageAsync(string in0)
        {
            return base.Channel.getJobtitleInfoWithPageAsync(in0);
        }
        
        public System.Threading.Tasks.Task<string> SynHrmResourceAsync(string in0, string in1)
        {
            return base.Channel.SynHrmResourceAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.DepartmentBean[]> getHrmDepartmentInfoAsync(string in0, string in1)
        {
            return base.Channel.getHrmDepartmentInfoAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<string> getHrmUserInfoWithPageAsync(string in0)
        {
            return base.Channel.getHrmUserInfoWithPageAsync(in0);
        }
        
        public System.Threading.Tasks.Task<string> getHrmSubcompanyInfoWithPageAsync(string in0)
        {
            return base.Channel.getHrmSubcompanyInfoWithPageAsync(in0);
        }
        
        public System.Threading.Tasks.Task<string> SynJobtitleAsync(string in0, string in1)
        {
            return base.Channel.SynJobtitleAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<string> getHrmSubcompanyInfoXMLAsync(string in0)
        {
            return base.Channel.getHrmSubcompanyInfoXMLAsync(in0);
        }
        
        public System.Threading.Tasks.Task<string> getHrmUserInfoXMLAsync(string in0, string in1, string in2, string in3, string in4, string in5)
        {
            return base.Channel.getHrmUserInfoXMLAsync(in0, in1, in2, in3, in4, in5);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HrmServiceHttpPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HrmServiceHttpPort))
            {
                return new System.ServiceModel.EndpointAddress("http://172.22.156.3:14058/services/HrmService");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return HrmServicePortTypeClient.GetBindingForEndpoint(EndpointConfiguration.HrmServiceHttpPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return HrmServicePortTypeClient.GetEndpointAddress(EndpointConfiguration.HrmServiceHttpPort);
        }
        
        public enum EndpointConfiguration
        {
            
            HrmServiceHttpPort,
        }
    }
}
