version: '3.3'
services:
  service2:
    build:
      context: ~/Doublehis 
    image: doublehis
    ports:
      - 8800:7500/tcp
    command: ["dotnet", "/app/HISDouble.dll"]
  service3:
    image: doublehis
    ports:
      - 7001:7500/tcp
    command: ["dotnet", "/app/HISDouble.dll"]
  nginx:
    image: nginx:latest
    ports:
      - 7000:80/tcp
    volumes:
      - ~/Doublehis/nginx/nginx.conf:/etc/nginx/nginx.conf
       - ./conf.d:/etc/nginx/conf.d
       - ./logs:/var/log/nginx
      #docker 重启后，容器自启动
     restart: always